Feature/tapis etl package
tapis-project/tapisv3-cli pull request #59
Opened 2024-04-11 21:51 UTC by tacc-afields

### Overview:

### Github Issue Links:
[Task <task#>](https://github.com/tapis-project/tapisv3-cli/issues/<task#>)

### Summary of changes:
-

### Steps-to-test:
-

### Notes:

2024-04-11 21:54 UTC, tacc-afields commented
I forgot to do a git pull origin dev before doing this pull frequest: I closed this, ran GPOD, it said I was up to date with the branch so I am reopening this.

2024-04-24 14:19 UTC, nathandf requested changes

2024-04-24 14:19 UTC, nathandf commented on src/packages/tapisetl/controllers/DataValidator.py
I think we should remove this entirely for now.

2024-04-24 14:19 UTC, nathandf commented on src/packages/tapisetl/controllers/Index.py
> +    directories = {}
Remove. Doesn't look like there is any use for this attribute. Also, I generally don't use class attributes for anything.

2024-04-24 15:06 UTC, nathandf approved these changes

2024-04-24 15:06 UTC, merged